[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#DCDCDC"
font = "sans serif"

[server]
runOnSave = true
port = 8501
address = "0.0.0.0"
headless = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
